// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhYDiDhz8x8HHimUUtGYAvy0zGDiTahso',
    appId: '1:785094581158:web:01a502103d8b18927d0d67',
    messagingSenderId: '785094581158',
    projectId: 'ai-flutter-8e9e0',
    authDomain: 'ai-flutter-8e9e0.firebaseapp.com',
    storageBucket: 'ai-flutter-8e9e0.firebasestorage.app',
    measurementId: 'G-E7CYVW46CR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNlgAQqDbl8yJFZXSBD3fgoCXl5RmAa_Q',
    appId: '1:785094581158:android:477f17557875df317d0d67',
    messagingSenderId: '785094581158',
    projectId: 'ai-flutter-8e9e0',
    storageBucket: 'ai-flutter-8e9e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGurP4vKwxu6Zael3HBTnKEzi786j2UOc',
    appId: '1:785094581158:ios:12e7da9d90338c407d0d67',
    messagingSenderId: '785094581158',
    projectId: 'ai-flutter-8e9e0',
    storageBucket: 'ai-flutter-8e9e0.firebasestorage.app',
    androidClientId: '785094581158-d7nqu9o6dnoqdfamfppkko76d2sfs0gk.apps.googleusercontent.com',
    iosClientId: '785094581158-jv88t3cghp235rsadmech7vg7do7isnv.apps.googleusercontent.com',
    iosBundleId: 'com.example.prabir.ApolloApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGurP4vKwxu6Zael3HBTnKEzi786j2UOc',
    appId: '1:785094581158:ios:3c6661007ac2bb467d0d67',
    messagingSenderId: '785094581158',
    projectId: 'ai-flutter-8e9e0',
    storageBucket: 'ai-flutter-8e9e0.firebasestorage.app',
    androidClientId: '785094581158-d7nqu9o6dnoqdfamfppkko76d2sfs0gk.apps.googleusercontent.com',
    iosClientId: '785094581158-bmr8t25ar4ravdpftjekcjqvpd5hdh3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.apolloApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhYDiDhz8x8HHimUUtGYAvy0zGDiTahso',
    appId: '1:785094581158:web:16c3747e0dc1c1357d0d67',
    messagingSenderId: '785094581158',
    projectId: 'ai-flutter-8e9e0',
    authDomain: 'ai-flutter-8e9e0.firebaseapp.com',
    storageBucket: 'ai-flutter-8e9e0.firebasestorage.app',
    measurementId: 'G-Q4RB15K1JG',
  );

}