name: Docker-Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up secrets as files
        run: |
          echo "${{ secrets.CREDENTIALS }}" > server/credentials.json
          echo "${{ secrets.FIREBASESERVICE }}" > server/firebaseservice.json

      - name: Build docker image
        run: docker build -t prabirkalwani/apollo ./server

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Publish image to Docker Hub
        run: docker push prabirkalwani/apollo:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: sudo docker pull prabirkalwani/apollo:latest

      - name: Delete old container
        run: sudo docker rm -f apollo

      - name: Run Docker container
        run: sudo docker run -d -p 8080:5000 --name apollo prabirkalwani/apollo:latest
